#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_adopciones")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Inserttbl_adoptante(tbl_adoptante instance);
    partial void Updatetbl_adoptante(tbl_adoptante instance);
    partial void Deletetbl_adoptante(tbl_adoptante instance);
    partial void Inserttbl_candidato(tbl_candidato instance);
    partial void Updatetbl_candidato(tbl_candidato instance);
    partial void Deletetbl_candidato(tbl_candidato instance);
    partial void Inserttbl_candidato_tutor(tbl_candidato_tutor instance);
    partial void Updatetbl_candidato_tutor(tbl_candidato_tutor instance);
    partial void Deletetbl_candidato_tutor(tbl_candidato_tutor instance);
    partial void Inserttbl_canditado_adoptante(tbl_canditado_adoptante instance);
    partial void Updatetbl_canditado_adoptante(tbl_canditado_adoptante instance);
    partial void Deletetbl_canditado_adoptante(tbl_canditado_adoptante instance);
    partial void Inserttbl_desparacitacion(tbl_desparacitacion instance);
    partial void Updatetbl_desparacitacion(tbl_desparacitacion instance);
    partial void Deletetbl_desparacitacion(tbl_desparacitacion instance);
    partial void Inserttbl_especie(tbl_especie instance);
    partial void Updatetbl_especie(tbl_especie instance);
    partial void Deletetbl_especie(tbl_especie instance);
    partial void Inserttbl_historia_clinica(tbl_historia_clinica instance);
    partial void Updatetbl_historia_clinica(tbl_historia_clinica instance);
    partial void Deletetbl_historia_clinica(tbl_historia_clinica instance);
    partial void Inserttbl_personas(tbl_personas instance);
    partial void Updatetbl_personas(tbl_personas instance);
    partial void Deletetbl_personas(tbl_personas instance);
    partial void Inserttbl_raza(tbl_raza instance);
    partial void Updatetbl_raza(tbl_raza instance);
    partial void Deletetbl_raza(tbl_raza instance);
    partial void Inserttbl_rol(tbl_rol instance);
    partial void Updatetbl_rol(tbl_rol instance);
    partial void Deletetbl_rol(tbl_rol instance);
    partial void Inserttbl_tutor(tbl_tutor instance);
    partial void Updatetbl_tutor(tbl_tutor instance);
    partial void Deletetbl_tutor(tbl_tutor instance);
    partial void Inserttbl_vacunacion(tbl_vacunacion instance);
    partial void Updatetbl_vacunacion(tbl_vacunacion instance);
    partial void Deletetbl_vacunacion(tbl_vacunacion instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::CapaDatos.Properties.Settings.Default.db_adopcionesConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_adoptante> tbl_adoptante
		{
			get
			{
				return this.GetTable<tbl_adoptante>();
			}
		}
		
		public System.Data.Linq.Table<tbl_candidato> tbl_candidato
		{
			get
			{
				return this.GetTable<tbl_candidato>();
			}
		}
		
		public System.Data.Linq.Table<tbl_candidato_tutor> tbl_candidato_tutor
		{
			get
			{
				return this.GetTable<tbl_candidato_tutor>();
			}
		}
		
		public System.Data.Linq.Table<tbl_canditado_adoptante> tbl_canditado_adoptante
		{
			get
			{
				return this.GetTable<tbl_canditado_adoptante>();
			}
		}
		
		public System.Data.Linq.Table<tbl_desparacitacion> tbl_desparacitacion
		{
			get
			{
				return this.GetTable<tbl_desparacitacion>();
			}
		}
		
		public System.Data.Linq.Table<tbl_especie> tbl_especie
		{
			get
			{
				return this.GetTable<tbl_especie>();
			}
		}
		
		public System.Data.Linq.Table<tbl_historia_clinica> tbl_historia_clinica
		{
			get
			{
				return this.GetTable<tbl_historia_clinica>();
			}
		}
		
		public System.Data.Linq.Table<tbl_personas> tbl_personas
		{
			get
			{
				return this.GetTable<tbl_personas>();
			}
		}
		
		public System.Data.Linq.Table<tbl_raza> tbl_raza
		{
			get
			{
				return this.GetTable<tbl_raza>();
			}
		}
		
		public System.Data.Linq.Table<tbl_rol> tbl_rol
		{
			get
			{
				return this.GetTable<tbl_rol>();
			}
		}
		
		public System.Data.Linq.Table<tbl_tutor> tbl_tutor
		{
			get
			{
				return this.GetTable<tbl_tutor>();
			}
		}
		
		public System.Data.Linq.Table<tbl_vacunacion> tbl_vacunacion
		{
			get
			{
				return this.GetTable<tbl_vacunacion>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_Login")]
		public ISingleResult<Sp_LoginResult> Sp_Login()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Sp_LoginResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_Registro")]
		public ISingleResult<Sp_RegistroResult> Sp_Registro()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Sp_RegistroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_InsertarUsuario")]
		public int Sp_InsertarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string clave, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> estado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string temporal)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario, clave, estado, email, temporal);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_BuscarClaveTem")]
		public ISingleResult<Sp_BuscarClaveTemResult> Sp_BuscarClaveTem()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Sp_BuscarClaveTemResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_BuscarIdUsu")]
		public ISingleResult<Sp_BuscarIdUsuResult> Sp_BuscarIdUsu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string cltem)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cltem);
			return ((ISingleResult<Sp_BuscarIdUsuResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_adoptante")]
	public partial class tbl_adoptante : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_adop;
		
		private System.Nullable<char> _est_adop;
		
		private System.Nullable<int> _int_persona;
		
		private EntitySet<tbl_canditado_adoptante> _tbl_canditado_adoptante;
		
		private EntityRef<tbl_personas> _tbl_personas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_adopChanging(int value);
    partial void Onid_adopChanged();
    partial void Onest_adopChanging(System.Nullable<char> value);
    partial void Onest_adopChanged();
    partial void Onint_personaChanging(System.Nullable<int> value);
    partial void Onint_personaChanged();
    #endregion
		
		public tbl_adoptante()
		{
			this._tbl_canditado_adoptante = new EntitySet<tbl_canditado_adoptante>(new Action<tbl_canditado_adoptante>(this.attach_tbl_canditado_adoptante), new Action<tbl_canditado_adoptante>(this.detach_tbl_canditado_adoptante));
			this._tbl_personas = default(EntityRef<tbl_personas>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_adop", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_adop
		{
			get
			{
				return this._id_adop;
			}
			set
			{
				if ((this._id_adop != value))
				{
					this.Onid_adopChanging(value);
					this.SendPropertyChanging();
					this._id_adop = value;
					this.SendPropertyChanged("id_adop");
					this.Onid_adopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_est_adop", DbType="Char(1)")]
		public System.Nullable<char> est_adop
		{
			get
			{
				return this._est_adop;
			}
			set
			{
				if ((this._est_adop != value))
				{
					this.Onest_adopChanging(value);
					this.SendPropertyChanging();
					this._est_adop = value;
					this.SendPropertyChanged("est_adop");
					this.Onest_adopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_persona", DbType="Int")]
		public System.Nullable<int> int_persona
		{
			get
			{
				return this._int_persona;
			}
			set
			{
				if ((this._int_persona != value))
				{
					if (this._tbl_personas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onint_personaChanging(value);
					this.SendPropertyChanging();
					this._int_persona = value;
					this.SendPropertyChanged("int_persona");
					this.Onint_personaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_adoptante_tbl_canditado_adoptante", Storage="_tbl_canditado_adoptante", ThisKey="id_adop", OtherKey="id_adoptante")]
		public EntitySet<tbl_canditado_adoptante> tbl_canditado_adoptante
		{
			get
			{
				return this._tbl_canditado_adoptante;
			}
			set
			{
				this._tbl_canditado_adoptante.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_personas_tbl_adoptante", Storage="_tbl_personas", ThisKey="int_persona", OtherKey="id_per", IsForeignKey=true)]
		public tbl_personas tbl_personas
		{
			get
			{
				return this._tbl_personas.Entity;
			}
			set
			{
				tbl_personas previousValue = this._tbl_personas.Entity;
				if (((previousValue != value) 
							|| (this._tbl_personas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_personas.Entity = null;
						previousValue.tbl_adoptante.Remove(this);
					}
					this._tbl_personas.Entity = value;
					if ((value != null))
					{
						value.tbl_adoptante.Add(this);
						this._int_persona = value.id_per;
					}
					else
					{
						this._int_persona = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_personas");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_canditado_adoptante(tbl_canditado_adoptante entity)
		{
			this.SendPropertyChanging();
			entity.tbl_adoptante = this;
		}
		
		private void detach_tbl_canditado_adoptante(tbl_canditado_adoptante entity)
		{
			this.SendPropertyChanging();
			entity.tbl_adoptante = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_candidato")]
	public partial class tbl_candidato : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _des_can;
		
		private string _orig_can;
		
		private string _nom_can;
		
		private string _img_can;
		
		private string _qrcd_can;
		
		private System.Nullable<char> _est_can;
		
		private int _id_can;
		
		private System.Nullable<int> _id_historiaclinica;
		
		private EntitySet<tbl_candidato_tutor> _tbl_candidato_tutor;
		
		private EntitySet<tbl_canditado_adoptante> _tbl_canditado_adoptante;
		
		private EntityRef<tbl_historia_clinica> _tbl_historia_clinica;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondes_canChanging(string value);
    partial void Ondes_canChanged();
    partial void Onorig_canChanging(string value);
    partial void Onorig_canChanged();
    partial void Onnom_canChanging(string value);
    partial void Onnom_canChanged();
    partial void Onimg_canChanging(string value);
    partial void Onimg_canChanged();
    partial void Onqrcd_canChanging(string value);
    partial void Onqrcd_canChanged();
    partial void Onest_canChanging(System.Nullable<char> value);
    partial void Onest_canChanged();
    partial void Onid_canChanging(int value);
    partial void Onid_canChanged();
    partial void Onid_historiaclinicaChanging(System.Nullable<int> value);
    partial void Onid_historiaclinicaChanged();
    #endregion
		
		public tbl_candidato()
		{
			this._tbl_candidato_tutor = new EntitySet<tbl_candidato_tutor>(new Action<tbl_candidato_tutor>(this.attach_tbl_candidato_tutor), new Action<tbl_candidato_tutor>(this.detach_tbl_candidato_tutor));
			this._tbl_canditado_adoptante = new EntitySet<tbl_canditado_adoptante>(new Action<tbl_canditado_adoptante>(this.attach_tbl_canditado_adoptante), new Action<tbl_canditado_adoptante>(this.detach_tbl_canditado_adoptante));
			this._tbl_historia_clinica = default(EntityRef<tbl_historia_clinica>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_des_can", DbType="VarChar(200)")]
		public string des_can
		{
			get
			{
				return this._des_can;
			}
			set
			{
				if ((this._des_can != value))
				{
					this.Ondes_canChanging(value);
					this.SendPropertyChanging();
					this._des_can = value;
					this.SendPropertyChanged("des_can");
					this.Ondes_canChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orig_can", DbType="VarChar(100)")]
		public string orig_can
		{
			get
			{
				return this._orig_can;
			}
			set
			{
				if ((this._orig_can != value))
				{
					this.Onorig_canChanging(value);
					this.SendPropertyChanging();
					this._orig_can = value;
					this.SendPropertyChanged("orig_can");
					this.Onorig_canChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom_can", DbType="VarChar(50)")]
		public string nom_can
		{
			get
			{
				return this._nom_can;
			}
			set
			{
				if ((this._nom_can != value))
				{
					this.Onnom_canChanging(value);
					this.SendPropertyChanging();
					this._nom_can = value;
					this.SendPropertyChanged("nom_can");
					this.Onnom_canChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img_can", DbType="VarChar(100)")]
		public string img_can
		{
			get
			{
				return this._img_can;
			}
			set
			{
				if ((this._img_can != value))
				{
					this.Onimg_canChanging(value);
					this.SendPropertyChanging();
					this._img_can = value;
					this.SendPropertyChanged("img_can");
					this.Onimg_canChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qrcd_can", DbType="VarChar(100)")]
		public string qrcd_can
		{
			get
			{
				return this._qrcd_can;
			}
			set
			{
				if ((this._qrcd_can != value))
				{
					this.Onqrcd_canChanging(value);
					this.SendPropertyChanging();
					this._qrcd_can = value;
					this.SendPropertyChanged("qrcd_can");
					this.Onqrcd_canChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_est_can", DbType="Char(1)")]
		public System.Nullable<char> est_can
		{
			get
			{
				return this._est_can;
			}
			set
			{
				if ((this._est_can != value))
				{
					this.Onest_canChanging(value);
					this.SendPropertyChanging();
					this._est_can = value;
					this.SendPropertyChanged("est_can");
					this.Onest_canChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_can", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_can
		{
			get
			{
				return this._id_can;
			}
			set
			{
				if ((this._id_can != value))
				{
					this.Onid_canChanging(value);
					this.SendPropertyChanging();
					this._id_can = value;
					this.SendPropertyChanged("id_can");
					this.Onid_canChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_historiaclinica", DbType="Int")]
		public System.Nullable<int> id_historiaclinica
		{
			get
			{
				return this._id_historiaclinica;
			}
			set
			{
				if ((this._id_historiaclinica != value))
				{
					if (this._tbl_historia_clinica.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_historiaclinicaChanging(value);
					this.SendPropertyChanging();
					this._id_historiaclinica = value;
					this.SendPropertyChanged("id_historiaclinica");
					this.Onid_historiaclinicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_candidato_tbl_candidato_tutor", Storage="_tbl_candidato_tutor", ThisKey="id_can", OtherKey="id_candidato")]
		public EntitySet<tbl_candidato_tutor> tbl_candidato_tutor
		{
			get
			{
				return this._tbl_candidato_tutor;
			}
			set
			{
				this._tbl_candidato_tutor.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_candidato_tbl_canditado_adoptante", Storage="_tbl_canditado_adoptante", ThisKey="id_can", OtherKey="id_cadidato")]
		public EntitySet<tbl_canditado_adoptante> tbl_canditado_adoptante
		{
			get
			{
				return this._tbl_canditado_adoptante;
			}
			set
			{
				this._tbl_canditado_adoptante.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_historia_clinica_tbl_candidato", Storage="_tbl_historia_clinica", ThisKey="id_historiaclinica", OtherKey="id_htcl", IsForeignKey=true)]
		public tbl_historia_clinica tbl_historia_clinica
		{
			get
			{
				return this._tbl_historia_clinica.Entity;
			}
			set
			{
				tbl_historia_clinica previousValue = this._tbl_historia_clinica.Entity;
				if (((previousValue != value) 
							|| (this._tbl_historia_clinica.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_historia_clinica.Entity = null;
						previousValue.tbl_candidato.Remove(this);
					}
					this._tbl_historia_clinica.Entity = value;
					if ((value != null))
					{
						value.tbl_candidato.Add(this);
						this._id_historiaclinica = value.id_htcl;
					}
					else
					{
						this._id_historiaclinica = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_historia_clinica");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_candidato_tutor(tbl_candidato_tutor entity)
		{
			this.SendPropertyChanging();
			entity.tbl_candidato = this;
		}
		
		private void detach_tbl_candidato_tutor(tbl_candidato_tutor entity)
		{
			this.SendPropertyChanging();
			entity.tbl_candidato = null;
		}
		
		private void attach_tbl_canditado_adoptante(tbl_canditado_adoptante entity)
		{
			this.SendPropertyChanging();
			entity.tbl_candidato = this;
		}
		
		private void detach_tbl_canditado_adoptante(tbl_canditado_adoptante entity)
		{
			this.SendPropertyChanging();
			entity.tbl_candidato = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_candidato_tutor")]
	public partial class tbl_candidato_tutor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_ca_tut;
		
		private System.Nullable<int> _id_candidato;
		
		private System.Nullable<int> _id_tutor;
		
		private System.Nullable<char> _est_can_tut;
		
		private EntityRef<tbl_candidato> _tbl_candidato;
		
		private EntityRef<tbl_tutor> _tbl_tutor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_ca_tutChanging(int value);
    partial void Onid_ca_tutChanged();
    partial void Onid_candidatoChanging(System.Nullable<int> value);
    partial void Onid_candidatoChanged();
    partial void Onid_tutorChanging(System.Nullable<int> value);
    partial void Onid_tutorChanged();
    partial void Onest_can_tutChanging(System.Nullable<char> value);
    partial void Onest_can_tutChanged();
    #endregion
		
		public tbl_candidato_tutor()
		{
			this._tbl_candidato = default(EntityRef<tbl_candidato>);
			this._tbl_tutor = default(EntityRef<tbl_tutor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ca_tut", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_ca_tut
		{
			get
			{
				return this._id_ca_tut;
			}
			set
			{
				if ((this._id_ca_tut != value))
				{
					this.Onid_ca_tutChanging(value);
					this.SendPropertyChanging();
					this._id_ca_tut = value;
					this.SendPropertyChanged("id_ca_tut");
					this.Onid_ca_tutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_candidato", DbType="Int")]
		public System.Nullable<int> id_candidato
		{
			get
			{
				return this._id_candidato;
			}
			set
			{
				if ((this._id_candidato != value))
				{
					if (this._tbl_candidato.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_candidatoChanging(value);
					this.SendPropertyChanging();
					this._id_candidato = value;
					this.SendPropertyChanged("id_candidato");
					this.Onid_candidatoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tutor", DbType="Int")]
		public System.Nullable<int> id_tutor
		{
			get
			{
				return this._id_tutor;
			}
			set
			{
				if ((this._id_tutor != value))
				{
					if (this._tbl_tutor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_tutorChanging(value);
					this.SendPropertyChanging();
					this._id_tutor = value;
					this.SendPropertyChanged("id_tutor");
					this.Onid_tutorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_est_can_tut", DbType="Char(1)")]
		public System.Nullable<char> est_can_tut
		{
			get
			{
				return this._est_can_tut;
			}
			set
			{
				if ((this._est_can_tut != value))
				{
					this.Onest_can_tutChanging(value);
					this.SendPropertyChanging();
					this._est_can_tut = value;
					this.SendPropertyChanged("est_can_tut");
					this.Onest_can_tutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_candidato_tbl_candidato_tutor", Storage="_tbl_candidato", ThisKey="id_candidato", OtherKey="id_can", IsForeignKey=true)]
		public tbl_candidato tbl_candidato
		{
			get
			{
				return this._tbl_candidato.Entity;
			}
			set
			{
				tbl_candidato previousValue = this._tbl_candidato.Entity;
				if (((previousValue != value) 
							|| (this._tbl_candidato.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_candidato.Entity = null;
						previousValue.tbl_candidato_tutor.Remove(this);
					}
					this._tbl_candidato.Entity = value;
					if ((value != null))
					{
						value.tbl_candidato_tutor.Add(this);
						this._id_candidato = value.id_can;
					}
					else
					{
						this._id_candidato = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_candidato");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_tutor_tbl_candidato_tutor", Storage="_tbl_tutor", ThisKey="id_tutor", OtherKey="id_tut", IsForeignKey=true)]
		public tbl_tutor tbl_tutor
		{
			get
			{
				return this._tbl_tutor.Entity;
			}
			set
			{
				tbl_tutor previousValue = this._tbl_tutor.Entity;
				if (((previousValue != value) 
							|| (this._tbl_tutor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_tutor.Entity = null;
						previousValue.tbl_candidato_tutor.Remove(this);
					}
					this._tbl_tutor.Entity = value;
					if ((value != null))
					{
						value.tbl_candidato_tutor.Add(this);
						this._id_tutor = value.id_tut;
					}
					else
					{
						this._id_tutor = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_tutor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_canditado_adoptante")]
	public partial class tbl_canditado_adoptante : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_can_ado;
		
		private System.Nullable<int> _id_cadidato;
		
		private System.Nullable<int> _id_adoptante;
		
		private System.Nullable<char> _est_can_ado;
		
		private EntityRef<tbl_adoptante> _tbl_adoptante;
		
		private EntityRef<tbl_candidato> _tbl_candidato;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_can_adoChanging(int value);
    partial void Onid_can_adoChanged();
    partial void Onid_cadidatoChanging(System.Nullable<int> value);
    partial void Onid_cadidatoChanged();
    partial void Onid_adoptanteChanging(System.Nullable<int> value);
    partial void Onid_adoptanteChanged();
    partial void Onest_can_adoChanging(System.Nullable<char> value);
    partial void Onest_can_adoChanged();
    #endregion
		
		public tbl_canditado_adoptante()
		{
			this._tbl_adoptante = default(EntityRef<tbl_adoptante>);
			this._tbl_candidato = default(EntityRef<tbl_candidato>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_can_ado", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_can_ado
		{
			get
			{
				return this._id_can_ado;
			}
			set
			{
				if ((this._id_can_ado != value))
				{
					this.Onid_can_adoChanging(value);
					this.SendPropertyChanging();
					this._id_can_ado = value;
					this.SendPropertyChanged("id_can_ado");
					this.Onid_can_adoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cadidato", DbType="Int")]
		public System.Nullable<int> id_cadidato
		{
			get
			{
				return this._id_cadidato;
			}
			set
			{
				if ((this._id_cadidato != value))
				{
					if (this._tbl_candidato.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_cadidatoChanging(value);
					this.SendPropertyChanging();
					this._id_cadidato = value;
					this.SendPropertyChanged("id_cadidato");
					this.Onid_cadidatoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_adoptante", DbType="Int")]
		public System.Nullable<int> id_adoptante
		{
			get
			{
				return this._id_adoptante;
			}
			set
			{
				if ((this._id_adoptante != value))
				{
					if (this._tbl_adoptante.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_adoptanteChanging(value);
					this.SendPropertyChanging();
					this._id_adoptante = value;
					this.SendPropertyChanged("id_adoptante");
					this.Onid_adoptanteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_est_can_ado", DbType="Char(1)")]
		public System.Nullable<char> est_can_ado
		{
			get
			{
				return this._est_can_ado;
			}
			set
			{
				if ((this._est_can_ado != value))
				{
					this.Onest_can_adoChanging(value);
					this.SendPropertyChanging();
					this._est_can_ado = value;
					this.SendPropertyChanged("est_can_ado");
					this.Onest_can_adoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_adoptante_tbl_canditado_adoptante", Storage="_tbl_adoptante", ThisKey="id_adoptante", OtherKey="id_adop", IsForeignKey=true)]
		public tbl_adoptante tbl_adoptante
		{
			get
			{
				return this._tbl_adoptante.Entity;
			}
			set
			{
				tbl_adoptante previousValue = this._tbl_adoptante.Entity;
				if (((previousValue != value) 
							|| (this._tbl_adoptante.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_adoptante.Entity = null;
						previousValue.tbl_canditado_adoptante.Remove(this);
					}
					this._tbl_adoptante.Entity = value;
					if ((value != null))
					{
						value.tbl_canditado_adoptante.Add(this);
						this._id_adoptante = value.id_adop;
					}
					else
					{
						this._id_adoptante = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_adoptante");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_candidato_tbl_canditado_adoptante", Storage="_tbl_candidato", ThisKey="id_cadidato", OtherKey="id_can", IsForeignKey=true)]
		public tbl_candidato tbl_candidato
		{
			get
			{
				return this._tbl_candidato.Entity;
			}
			set
			{
				tbl_candidato previousValue = this._tbl_candidato.Entity;
				if (((previousValue != value) 
							|| (this._tbl_candidato.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_candidato.Entity = null;
						previousValue.tbl_canditado_adoptante.Remove(this);
					}
					this._tbl_candidato.Entity = value;
					if ((value != null))
					{
						value.tbl_canditado_adoptante.Add(this);
						this._id_cadidato = value.id_can;
					}
					else
					{
						this._id_cadidato = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_candidato");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_desparacitacion")]
	public partial class tbl_desparacitacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_des;
		
		private string _des_des;
		
		private System.Nullable<System.DateTime> _fec_des;
		
		private System.Nullable<char> _est_des;
		
		private EntitySet<tbl_historia_clinica> _tbl_historia_clinica;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_desChanging(int value);
    partial void Onid_desChanged();
    partial void Ondes_desChanging(string value);
    partial void Ondes_desChanged();
    partial void Onfec_desChanging(System.Nullable<System.DateTime> value);
    partial void Onfec_desChanged();
    partial void Onest_desChanging(System.Nullable<char> value);
    partial void Onest_desChanged();
    #endregion
		
		public tbl_desparacitacion()
		{
			this._tbl_historia_clinica = new EntitySet<tbl_historia_clinica>(new Action<tbl_historia_clinica>(this.attach_tbl_historia_clinica), new Action<tbl_historia_clinica>(this.detach_tbl_historia_clinica));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_des", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_des
		{
			get
			{
				return this._id_des;
			}
			set
			{
				if ((this._id_des != value))
				{
					this.Onid_desChanging(value);
					this.SendPropertyChanging();
					this._id_des = value;
					this.SendPropertyChanged("id_des");
					this.Onid_desChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_des_des", DbType="VarChar(100)")]
		public string des_des
		{
			get
			{
				return this._des_des;
			}
			set
			{
				if ((this._des_des != value))
				{
					this.Ondes_desChanging(value);
					this.SendPropertyChanging();
					this._des_des = value;
					this.SendPropertyChanged("des_des");
					this.Ondes_desChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fec_des", DbType="Date")]
		public System.Nullable<System.DateTime> fec_des
		{
			get
			{
				return this._fec_des;
			}
			set
			{
				if ((this._fec_des != value))
				{
					this.Onfec_desChanging(value);
					this.SendPropertyChanging();
					this._fec_des = value;
					this.SendPropertyChanged("fec_des");
					this.Onfec_desChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_est_des", DbType="Char(1)")]
		public System.Nullable<char> est_des
		{
			get
			{
				return this._est_des;
			}
			set
			{
				if ((this._est_des != value))
				{
					this.Onest_desChanging(value);
					this.SendPropertyChanging();
					this._est_des = value;
					this.SendPropertyChanged("est_des");
					this.Onest_desChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_desparacitacion_tbl_historia_clinica", Storage="_tbl_historia_clinica", ThisKey="id_des", OtherKey="id_desparacita")]
		public EntitySet<tbl_historia_clinica> tbl_historia_clinica
		{
			get
			{
				return this._tbl_historia_clinica;
			}
			set
			{
				this._tbl_historia_clinica.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_historia_clinica(tbl_historia_clinica entity)
		{
			this.SendPropertyChanging();
			entity.tbl_desparacitacion = this;
		}
		
		private void detach_tbl_historia_clinica(tbl_historia_clinica entity)
		{
			this.SendPropertyChanging();
			entity.tbl_desparacitacion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_especie")]
	public partial class tbl_especie : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_esp;
		
		private string _des_esp;
		
		private System.Nullable<char> _est_esp;
		
		private EntitySet<tbl_historia_clinica> _tbl_historia_clinica;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_espChanging(int value);
    partial void Onid_espChanged();
    partial void Ondes_espChanging(string value);
    partial void Ondes_espChanged();
    partial void Onest_espChanging(System.Nullable<char> value);
    partial void Onest_espChanged();
    #endregion
		
		public tbl_especie()
		{
			this._tbl_historia_clinica = new EntitySet<tbl_historia_clinica>(new Action<tbl_historia_clinica>(this.attach_tbl_historia_clinica), new Action<tbl_historia_clinica>(this.detach_tbl_historia_clinica));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_esp", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_esp
		{
			get
			{
				return this._id_esp;
			}
			set
			{
				if ((this._id_esp != value))
				{
					this.Onid_espChanging(value);
					this.SendPropertyChanging();
					this._id_esp = value;
					this.SendPropertyChanged("id_esp");
					this.Onid_espChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_des_esp", DbType="VarChar(1)")]
		public string des_esp
		{
			get
			{
				return this._des_esp;
			}
			set
			{
				if ((this._des_esp != value))
				{
					this.Ondes_espChanging(value);
					this.SendPropertyChanging();
					this._des_esp = value;
					this.SendPropertyChanged("des_esp");
					this.Ondes_espChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_est_esp", DbType="Char(1)")]
		public System.Nullable<char> est_esp
		{
			get
			{
				return this._est_esp;
			}
			set
			{
				if ((this._est_esp != value))
				{
					this.Onest_espChanging(value);
					this.SendPropertyChanging();
					this._est_esp = value;
					this.SendPropertyChanged("est_esp");
					this.Onest_espChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_especie_tbl_historia_clinica", Storage="_tbl_historia_clinica", ThisKey="id_esp", OtherKey="id_especie")]
		public EntitySet<tbl_historia_clinica> tbl_historia_clinica
		{
			get
			{
				return this._tbl_historia_clinica;
			}
			set
			{
				this._tbl_historia_clinica.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_historia_clinica(tbl_historia_clinica entity)
		{
			this.SendPropertyChanging();
			entity.tbl_especie = this;
		}
		
		private void detach_tbl_historia_clinica(tbl_historia_clinica entity)
		{
			this.SendPropertyChanging();
			entity.tbl_especie = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_historia_clinica")]
	public partial class tbl_historia_clinica : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _num_htcl;
		
		private System.Nullable<int> _id_especie;
		
		private System.Nullable<int> _id_raza;
		
		private System.Nullable<char> _sex_htcl;
		
		private string _eda_htcl;
		
		private string _cara_htcl;
		
		private System.Nullable<int> _id_vacunacion;
		
		private System.Nullable<int> _id_desparacita;
		
		private string _hist_htcl;
		
		private string _diet_htcl;
		
		private string _estrep_htcl;
		
		private string _proc_htcl;
		
		private System.Nullable<decimal> _pes_htcl;
		
		private System.Nullable<decimal> _tall_htcl;
		
		private string _enfe_htcl;
		
		private System.Nullable<char> _est_htcl;
		
		private int _id_htcl;
		
		private EntitySet<tbl_candidato> _tbl_candidato;
		
		private EntityRef<tbl_desparacitacion> _tbl_desparacitacion;
		
		private EntityRef<tbl_especie> _tbl_especie;
		
		private EntityRef<tbl_raza> _tbl_raza;
		
		private EntityRef<tbl_vacunacion> _tbl_vacunacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnum_htclChanging(string value);
    partial void Onnum_htclChanged();
    partial void Onid_especieChanging(System.Nullable<int> value);
    partial void Onid_especieChanged();
    partial void Onid_razaChanging(System.Nullable<int> value);
    partial void Onid_razaChanged();
    partial void Onsex_htclChanging(System.Nullable<char> value);
    partial void Onsex_htclChanged();
    partial void Oneda_htclChanging(string value);
    partial void Oneda_htclChanged();
    partial void Oncara_htclChanging(string value);
    partial void Oncara_htclChanged();
    partial void Onid_vacunacionChanging(System.Nullable<int> value);
    partial void Onid_vacunacionChanged();
    partial void Onid_desparacitaChanging(System.Nullable<int> value);
    partial void Onid_desparacitaChanged();
    partial void Onhist_htclChanging(string value);
    partial void Onhist_htclChanged();
    partial void Ondiet_htclChanging(string value);
    partial void Ondiet_htclChanged();
    partial void Onestrep_htclChanging(string value);
    partial void Onestrep_htclChanged();
    partial void Onproc_htclChanging(string value);
    partial void Onproc_htclChanged();
    partial void Onpes_htclChanging(System.Nullable<decimal> value);
    partial void Onpes_htclChanged();
    partial void Ontall_htclChanging(System.Nullable<decimal> value);
    partial void Ontall_htclChanged();
    partial void Onenfe_htclChanging(string value);
    partial void Onenfe_htclChanged();
    partial void Onest_htclChanging(System.Nullable<char> value);
    partial void Onest_htclChanged();
    partial void Onid_htclChanging(int value);
    partial void Onid_htclChanged();
    #endregion
		
		public tbl_historia_clinica()
		{
			this._tbl_candidato = new EntitySet<tbl_candidato>(new Action<tbl_candidato>(this.attach_tbl_candidato), new Action<tbl_candidato>(this.detach_tbl_candidato));
			this._tbl_desparacitacion = default(EntityRef<tbl_desparacitacion>);
			this._tbl_especie = default(EntityRef<tbl_especie>);
			this._tbl_raza = default(EntityRef<tbl_raza>);
			this._tbl_vacunacion = default(EntityRef<tbl_vacunacion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_htcl", DbType="VarChar(200)")]
		public string num_htcl
		{
			get
			{
				return this._num_htcl;
			}
			set
			{
				if ((this._num_htcl != value))
				{
					this.Onnum_htclChanging(value);
					this.SendPropertyChanging();
					this._num_htcl = value;
					this.SendPropertyChanged("num_htcl");
					this.Onnum_htclChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_especie", DbType="Int")]
		public System.Nullable<int> id_especie
		{
			get
			{
				return this._id_especie;
			}
			set
			{
				if ((this._id_especie != value))
				{
					if (this._tbl_especie.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_especieChanging(value);
					this.SendPropertyChanging();
					this._id_especie = value;
					this.SendPropertyChanged("id_especie");
					this.Onid_especieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_raza", DbType="Int")]
		public System.Nullable<int> id_raza
		{
			get
			{
				return this._id_raza;
			}
			set
			{
				if ((this._id_raza != value))
				{
					if (this._tbl_raza.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_razaChanging(value);
					this.SendPropertyChanging();
					this._id_raza = value;
					this.SendPropertyChanged("id_raza");
					this.Onid_razaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex_htcl", DbType="Char(1)")]
		public System.Nullable<char> sex_htcl
		{
			get
			{
				return this._sex_htcl;
			}
			set
			{
				if ((this._sex_htcl != value))
				{
					this.Onsex_htclChanging(value);
					this.SendPropertyChanging();
					this._sex_htcl = value;
					this.SendPropertyChanged("sex_htcl");
					this.Onsex_htclChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eda_htcl", DbType="VarChar(3)")]
		public string eda_htcl
		{
			get
			{
				return this._eda_htcl;
			}
			set
			{
				if ((this._eda_htcl != value))
				{
					this.Oneda_htclChanging(value);
					this.SendPropertyChanging();
					this._eda_htcl = value;
					this.SendPropertyChanged("eda_htcl");
					this.Oneda_htclChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cara_htcl", DbType="VarChar(50)")]
		public string cara_htcl
		{
			get
			{
				return this._cara_htcl;
			}
			set
			{
				if ((this._cara_htcl != value))
				{
					this.Oncara_htclChanging(value);
					this.SendPropertyChanging();
					this._cara_htcl = value;
					this.SendPropertyChanged("cara_htcl");
					this.Oncara_htclChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_vacunacion", DbType="Int")]
		public System.Nullable<int> id_vacunacion
		{
			get
			{
				return this._id_vacunacion;
			}
			set
			{
				if ((this._id_vacunacion != value))
				{
					if (this._tbl_vacunacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_vacunacionChanging(value);
					this.SendPropertyChanging();
					this._id_vacunacion = value;
					this.SendPropertyChanged("id_vacunacion");
					this.Onid_vacunacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_desparacita", DbType="Int")]
		public System.Nullable<int> id_desparacita
		{
			get
			{
				return this._id_desparacita;
			}
			set
			{
				if ((this._id_desparacita != value))
				{
					if (this._tbl_desparacitacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_desparacitaChanging(value);
					this.SendPropertyChanging();
					this._id_desparacita = value;
					this.SendPropertyChanged("id_desparacita");
					this.Onid_desparacitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hist_htcl", DbType="VarChar(200)")]
		public string hist_htcl
		{
			get
			{
				return this._hist_htcl;
			}
			set
			{
				if ((this._hist_htcl != value))
				{
					this.Onhist_htclChanging(value);
					this.SendPropertyChanging();
					this._hist_htcl = value;
					this.SendPropertyChanged("hist_htcl");
					this.Onhist_htclChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diet_htcl", DbType="VarChar(50)")]
		public string diet_htcl
		{
			get
			{
				return this._diet_htcl;
			}
			set
			{
				if ((this._diet_htcl != value))
				{
					this.Ondiet_htclChanging(value);
					this.SendPropertyChanging();
					this._diet_htcl = value;
					this.SendPropertyChanged("diet_htcl");
					this.Ondiet_htclChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estrep_htcl", DbType="VarChar(20)")]
		public string estrep_htcl
		{
			get
			{
				return this._estrep_htcl;
			}
			set
			{
				if ((this._estrep_htcl != value))
				{
					this.Onestrep_htclChanging(value);
					this.SendPropertyChanging();
					this._estrep_htcl = value;
					this.SendPropertyChanged("estrep_htcl");
					this.Onestrep_htclChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proc_htcl", DbType="VarChar(20)")]
		public string proc_htcl
		{
			get
			{
				return this._proc_htcl;
			}
			set
			{
				if ((this._proc_htcl != value))
				{
					this.Onproc_htclChanging(value);
					this.SendPropertyChanging();
					this._proc_htcl = value;
					this.SendPropertyChanged("proc_htcl");
					this.Onproc_htclChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pes_htcl", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> pes_htcl
		{
			get
			{
				return this._pes_htcl;
			}
			set
			{
				if ((this._pes_htcl != value))
				{
					this.Onpes_htclChanging(value);
					this.SendPropertyChanging();
					this._pes_htcl = value;
					this.SendPropertyChanged("pes_htcl");
					this.Onpes_htclChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tall_htcl", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> tall_htcl
		{
			get
			{
				return this._tall_htcl;
			}
			set
			{
				if ((this._tall_htcl != value))
				{
					this.Ontall_htclChanging(value);
					this.SendPropertyChanging();
					this._tall_htcl = value;
					this.SendPropertyChanged("tall_htcl");
					this.Ontall_htclChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enfe_htcl", DbType="VarChar(60)")]
		public string enfe_htcl
		{
			get
			{
				return this._enfe_htcl;
			}
			set
			{
				if ((this._enfe_htcl != value))
				{
					this.Onenfe_htclChanging(value);
					this.SendPropertyChanging();
					this._enfe_htcl = value;
					this.SendPropertyChanged("enfe_htcl");
					this.Onenfe_htclChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_est_htcl", DbType="Char(1)")]
		public System.Nullable<char> est_htcl
		{
			get
			{
				return this._est_htcl;
			}
			set
			{
				if ((this._est_htcl != value))
				{
					this.Onest_htclChanging(value);
					this.SendPropertyChanging();
					this._est_htcl = value;
					this.SendPropertyChanged("est_htcl");
					this.Onest_htclChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_htcl", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_htcl
		{
			get
			{
				return this._id_htcl;
			}
			set
			{
				if ((this._id_htcl != value))
				{
					this.Onid_htclChanging(value);
					this.SendPropertyChanging();
					this._id_htcl = value;
					this.SendPropertyChanged("id_htcl");
					this.Onid_htclChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_historia_clinica_tbl_candidato", Storage="_tbl_candidato", ThisKey="id_htcl", OtherKey="id_historiaclinica")]
		public EntitySet<tbl_candidato> tbl_candidato
		{
			get
			{
				return this._tbl_candidato;
			}
			set
			{
				this._tbl_candidato.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_desparacitacion_tbl_historia_clinica", Storage="_tbl_desparacitacion", ThisKey="id_desparacita", OtherKey="id_des", IsForeignKey=true)]
		public tbl_desparacitacion tbl_desparacitacion
		{
			get
			{
				return this._tbl_desparacitacion.Entity;
			}
			set
			{
				tbl_desparacitacion previousValue = this._tbl_desparacitacion.Entity;
				if (((previousValue != value) 
							|| (this._tbl_desparacitacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_desparacitacion.Entity = null;
						previousValue.tbl_historia_clinica.Remove(this);
					}
					this._tbl_desparacitacion.Entity = value;
					if ((value != null))
					{
						value.tbl_historia_clinica.Add(this);
						this._id_desparacita = value.id_des;
					}
					else
					{
						this._id_desparacita = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_desparacitacion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_especie_tbl_historia_clinica", Storage="_tbl_especie", ThisKey="id_especie", OtherKey="id_esp", IsForeignKey=true)]
		public tbl_especie tbl_especie
		{
			get
			{
				return this._tbl_especie.Entity;
			}
			set
			{
				tbl_especie previousValue = this._tbl_especie.Entity;
				if (((previousValue != value) 
							|| (this._tbl_especie.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_especie.Entity = null;
						previousValue.tbl_historia_clinica.Remove(this);
					}
					this._tbl_especie.Entity = value;
					if ((value != null))
					{
						value.tbl_historia_clinica.Add(this);
						this._id_especie = value.id_esp;
					}
					else
					{
						this._id_especie = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_especie");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_raza_tbl_historia_clinica", Storage="_tbl_raza", ThisKey="id_raza", OtherKey="id_raza", IsForeignKey=true)]
		public tbl_raza tbl_raza
		{
			get
			{
				return this._tbl_raza.Entity;
			}
			set
			{
				tbl_raza previousValue = this._tbl_raza.Entity;
				if (((previousValue != value) 
							|| (this._tbl_raza.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_raza.Entity = null;
						previousValue.tbl_historia_clinica.Remove(this);
					}
					this._tbl_raza.Entity = value;
					if ((value != null))
					{
						value.tbl_historia_clinica.Add(this);
						this._id_raza = value.id_raza;
					}
					else
					{
						this._id_raza = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_raza");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_vacunacion_tbl_historia_clinica", Storage="_tbl_vacunacion", ThisKey="id_vacunacion", OtherKey="id_vacu", IsForeignKey=true)]
		public tbl_vacunacion tbl_vacunacion
		{
			get
			{
				return this._tbl_vacunacion.Entity;
			}
			set
			{
				tbl_vacunacion previousValue = this._tbl_vacunacion.Entity;
				if (((previousValue != value) 
							|| (this._tbl_vacunacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_vacunacion.Entity = null;
						previousValue.tbl_historia_clinica.Remove(this);
					}
					this._tbl_vacunacion.Entity = value;
					if ((value != null))
					{
						value.tbl_historia_clinica.Add(this);
						this._id_vacunacion = value.id_vacu;
					}
					else
					{
						this._id_vacunacion = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_vacunacion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_candidato(tbl_candidato entity)
		{
			this.SendPropertyChanging();
			entity.tbl_historia_clinica = this;
		}
		
		private void detach_tbl_candidato(tbl_candidato entity)
		{
			this.SendPropertyChanging();
			entity.tbl_historia_clinica = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_personas")]
	public partial class tbl_personas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _dni_per;
		
		private string _nom_per;
		
		private string _ape_per;
		
		private string _tel_per;
		
		private string _ema_per;
		
		private string _cllp_per;
		
		private string _cll_sec_per;
		
		private string _numc_per;
		
		private string _est_per;
		
		private int _id_per;
		
		private System.Nullable<int> _id_ro;
		
		private EntitySet<tbl_adoptante> _tbl_adoptante;
		
		private EntitySet<tbl_tutor> _tbl_tutor;
		
		private EntityRef<tbl_rol> _tbl_rol;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondni_perChanging(string value);
    partial void Ondni_perChanged();
    partial void Onnom_perChanging(string value);
    partial void Onnom_perChanged();
    partial void Onape_perChanging(string value);
    partial void Onape_perChanged();
    partial void Ontel_perChanging(string value);
    partial void Ontel_perChanged();
    partial void Onema_perChanging(string value);
    partial void Onema_perChanged();
    partial void Oncllp_perChanging(string value);
    partial void Oncllp_perChanged();
    partial void Oncll_sec_perChanging(string value);
    partial void Oncll_sec_perChanged();
    partial void Onnumc_perChanging(string value);
    partial void Onnumc_perChanged();
    partial void Onest_perChanging(string value);
    partial void Onest_perChanged();
    partial void Onid_perChanging(int value);
    partial void Onid_perChanged();
    partial void Onid_roChanging(System.Nullable<int> value);
    partial void Onid_roChanged();
    #endregion
		
		public tbl_personas()
		{
			this._tbl_adoptante = new EntitySet<tbl_adoptante>(new Action<tbl_adoptante>(this.attach_tbl_adoptante), new Action<tbl_adoptante>(this.detach_tbl_adoptante));
			this._tbl_tutor = new EntitySet<tbl_tutor>(new Action<tbl_tutor>(this.attach_tbl_tutor), new Action<tbl_tutor>(this.detach_tbl_tutor));
			this._tbl_rol = default(EntityRef<tbl_rol>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dni_per", DbType="VarChar(10)")]
		public string dni_per
		{
			get
			{
				return this._dni_per;
			}
			set
			{
				if ((this._dni_per != value))
				{
					this.Ondni_perChanging(value);
					this.SendPropertyChanging();
					this._dni_per = value;
					this.SendPropertyChanged("dni_per");
					this.Ondni_perChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom_per", DbType="VarChar(20)")]
		public string nom_per
		{
			get
			{
				return this._nom_per;
			}
			set
			{
				if ((this._nom_per != value))
				{
					this.Onnom_perChanging(value);
					this.SendPropertyChanging();
					this._nom_per = value;
					this.SendPropertyChanged("nom_per");
					this.Onnom_perChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ape_per", DbType="VarChar(20)")]
		public string ape_per
		{
			get
			{
				return this._ape_per;
			}
			set
			{
				if ((this._ape_per != value))
				{
					this.Onape_perChanging(value);
					this.SendPropertyChanging();
					this._ape_per = value;
					this.SendPropertyChanged("ape_per");
					this.Onape_perChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel_per", DbType="VarChar(10)")]
		public string tel_per
		{
			get
			{
				return this._tel_per;
			}
			set
			{
				if ((this._tel_per != value))
				{
					this.Ontel_perChanging(value);
					this.SendPropertyChanging();
					this._tel_per = value;
					this.SendPropertyChanged("tel_per");
					this.Ontel_perChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ema_per", DbType="VarChar(100)")]
		public string ema_per
		{
			get
			{
				return this._ema_per;
			}
			set
			{
				if ((this._ema_per != value))
				{
					this.Onema_perChanging(value);
					this.SendPropertyChanging();
					this._ema_per = value;
					this.SendPropertyChanged("ema_per");
					this.Onema_perChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cllp_per", DbType="VarChar(20)")]
		public string cllp_per
		{
			get
			{
				return this._cllp_per;
			}
			set
			{
				if ((this._cllp_per != value))
				{
					this.Oncllp_perChanging(value);
					this.SendPropertyChanging();
					this._cllp_per = value;
					this.SendPropertyChanged("cllp_per");
					this.Oncllp_perChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cll_sec_per", DbType="VarChar(20)")]
		public string cll_sec_per
		{
			get
			{
				return this._cll_sec_per;
			}
			set
			{
				if ((this._cll_sec_per != value))
				{
					this.Oncll_sec_perChanging(value);
					this.SendPropertyChanging();
					this._cll_sec_per = value;
					this.SendPropertyChanged("cll_sec_per");
					this.Oncll_sec_perChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numc_per", DbType="VarChar(255)")]
		public string numc_per
		{
			get
			{
				return this._numc_per;
			}
			set
			{
				if ((this._numc_per != value))
				{
					this.Onnumc_perChanging(value);
					this.SendPropertyChanging();
					this._numc_per = value;
					this.SendPropertyChanged("numc_per");
					this.Onnumc_perChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_est_per", DbType="VarChar(255)")]
		public string est_per
		{
			get
			{
				return this._est_per;
			}
			set
			{
				if ((this._est_per != value))
				{
					this.Onest_perChanging(value);
					this.SendPropertyChanging();
					this._est_per = value;
					this.SendPropertyChanged("est_per");
					this.Onest_perChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_per", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_per
		{
			get
			{
				return this._id_per;
			}
			set
			{
				if ((this._id_per != value))
				{
					this.Onid_perChanging(value);
					this.SendPropertyChanging();
					this._id_per = value;
					this.SendPropertyChanged("id_per");
					this.Onid_perChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ro", DbType="Int")]
		public System.Nullable<int> id_ro
		{
			get
			{
				return this._id_ro;
			}
			set
			{
				if ((this._id_ro != value))
				{
					if (this._tbl_rol.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_roChanging(value);
					this.SendPropertyChanging();
					this._id_ro = value;
					this.SendPropertyChanged("id_ro");
					this.Onid_roChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_personas_tbl_adoptante", Storage="_tbl_adoptante", ThisKey="id_per", OtherKey="int_persona")]
		public EntitySet<tbl_adoptante> tbl_adoptante
		{
			get
			{
				return this._tbl_adoptante;
			}
			set
			{
				this._tbl_adoptante.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_personas_tbl_tutor", Storage="_tbl_tutor", ThisKey="id_per", OtherKey="id_persona")]
		public EntitySet<tbl_tutor> tbl_tutor
		{
			get
			{
				return this._tbl_tutor;
			}
			set
			{
				this._tbl_tutor.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_rol_tbl_personas", Storage="_tbl_rol", ThisKey="id_ro", OtherKey="id_rol", IsForeignKey=true)]
		public tbl_rol tbl_rol
		{
			get
			{
				return this._tbl_rol.Entity;
			}
			set
			{
				tbl_rol previousValue = this._tbl_rol.Entity;
				if (((previousValue != value) 
							|| (this._tbl_rol.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_rol.Entity = null;
						previousValue.tbl_personas.Remove(this);
					}
					this._tbl_rol.Entity = value;
					if ((value != null))
					{
						value.tbl_personas.Add(this);
						this._id_ro = value.id_rol;
					}
					else
					{
						this._id_ro = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_rol");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_adoptante(tbl_adoptante entity)
		{
			this.SendPropertyChanging();
			entity.tbl_personas = this;
		}
		
		private void detach_tbl_adoptante(tbl_adoptante entity)
		{
			this.SendPropertyChanging();
			entity.tbl_personas = null;
		}
		
		private void attach_tbl_tutor(tbl_tutor entity)
		{
			this.SendPropertyChanging();
			entity.tbl_personas = this;
		}
		
		private void detach_tbl_tutor(tbl_tutor entity)
		{
			this.SendPropertyChanging();
			entity.tbl_personas = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_raza")]
	public partial class tbl_raza : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_raza;
		
		private string _des_raza;
		
		private EntitySet<tbl_historia_clinica> _tbl_historia_clinica;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_razaChanging(int value);
    partial void Onid_razaChanged();
    partial void Ondes_razaChanging(string value);
    partial void Ondes_razaChanged();
    #endregion
		
		public tbl_raza()
		{
			this._tbl_historia_clinica = new EntitySet<tbl_historia_clinica>(new Action<tbl_historia_clinica>(this.attach_tbl_historia_clinica), new Action<tbl_historia_clinica>(this.detach_tbl_historia_clinica));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_raza", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_raza
		{
			get
			{
				return this._id_raza;
			}
			set
			{
				if ((this._id_raza != value))
				{
					this.Onid_razaChanging(value);
					this.SendPropertyChanging();
					this._id_raza = value;
					this.SendPropertyChanged("id_raza");
					this.Onid_razaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_des_raza", DbType="VarChar(50)")]
		public string des_raza
		{
			get
			{
				return this._des_raza;
			}
			set
			{
				if ((this._des_raza != value))
				{
					this.Ondes_razaChanging(value);
					this.SendPropertyChanging();
					this._des_raza = value;
					this.SendPropertyChanged("des_raza");
					this.Ondes_razaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_raza_tbl_historia_clinica", Storage="_tbl_historia_clinica", ThisKey="id_raza", OtherKey="id_raza")]
		public EntitySet<tbl_historia_clinica> tbl_historia_clinica
		{
			get
			{
				return this._tbl_historia_clinica;
			}
			set
			{
				this._tbl_historia_clinica.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_historia_clinica(tbl_historia_clinica entity)
		{
			this.SendPropertyChanging();
			entity.tbl_raza = this;
		}
		
		private void detach_tbl_historia_clinica(tbl_historia_clinica entity)
		{
			this.SendPropertyChanging();
			entity.tbl_raza = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_rol")]
	public partial class tbl_rol : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _des_rol;
		
		private System.Nullable<char> _est_rol;
		
		private int _id_rol;
		
		private EntitySet<tbl_personas> _tbl_personas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondes_rolChanging(string value);
    partial void Ondes_rolChanged();
    partial void Onest_rolChanging(System.Nullable<char> value);
    partial void Onest_rolChanged();
    partial void Onid_rolChanging(int value);
    partial void Onid_rolChanged();
    #endregion
		
		public tbl_rol()
		{
			this._tbl_personas = new EntitySet<tbl_personas>(new Action<tbl_personas>(this.attach_tbl_personas), new Action<tbl_personas>(this.detach_tbl_personas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_des_rol", DbType="VarChar(20)")]
		public string des_rol
		{
			get
			{
				return this._des_rol;
			}
			set
			{
				if ((this._des_rol != value))
				{
					this.Ondes_rolChanging(value);
					this.SendPropertyChanging();
					this._des_rol = value;
					this.SendPropertyChanged("des_rol");
					this.Ondes_rolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_est_rol", DbType="Char(1)")]
		public System.Nullable<char> est_rol
		{
			get
			{
				return this._est_rol;
			}
			set
			{
				if ((this._est_rol != value))
				{
					this.Onest_rolChanging(value);
					this.SendPropertyChanging();
					this._est_rol = value;
					this.SendPropertyChanged("est_rol");
					this.Onest_rolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_rol", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_rol
		{
			get
			{
				return this._id_rol;
			}
			set
			{
				if ((this._id_rol != value))
				{
					this.Onid_rolChanging(value);
					this.SendPropertyChanging();
					this._id_rol = value;
					this.SendPropertyChanged("id_rol");
					this.Onid_rolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_rol_tbl_personas", Storage="_tbl_personas", ThisKey="id_rol", OtherKey="id_ro")]
		public EntitySet<tbl_personas> tbl_personas
		{
			get
			{
				return this._tbl_personas;
			}
			set
			{
				this._tbl_personas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_personas(tbl_personas entity)
		{
			this.SendPropertyChanging();
			entity.tbl_rol = this;
		}
		
		private void detach_tbl_personas(tbl_personas entity)
		{
			this.SendPropertyChanging();
			entity.tbl_rol = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_tutor")]
	public partial class tbl_tutor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<char> _est_tut;
		
		private int _id_tut;
		
		private System.Nullable<int> _id_persona;
		
		private EntitySet<tbl_candidato_tutor> _tbl_candidato_tutor;
		
		private EntityRef<tbl_personas> _tbl_personas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onest_tutChanging(System.Nullable<char> value);
    partial void Onest_tutChanged();
    partial void Onid_tutChanging(int value);
    partial void Onid_tutChanged();
    partial void Onid_personaChanging(System.Nullable<int> value);
    partial void Onid_personaChanged();
    #endregion
		
		public tbl_tutor()
		{
			this._tbl_candidato_tutor = new EntitySet<tbl_candidato_tutor>(new Action<tbl_candidato_tutor>(this.attach_tbl_candidato_tutor), new Action<tbl_candidato_tutor>(this.detach_tbl_candidato_tutor));
			this._tbl_personas = default(EntityRef<tbl_personas>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_est_tut", DbType="Char(1)")]
		public System.Nullable<char> est_tut
		{
			get
			{
				return this._est_tut;
			}
			set
			{
				if ((this._est_tut != value))
				{
					this.Onest_tutChanging(value);
					this.SendPropertyChanging();
					this._est_tut = value;
					this.SendPropertyChanged("est_tut");
					this.Onest_tutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tut", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_tut
		{
			get
			{
				return this._id_tut;
			}
			set
			{
				if ((this._id_tut != value))
				{
					this.Onid_tutChanging(value);
					this.SendPropertyChanging();
					this._id_tut = value;
					this.SendPropertyChanged("id_tut");
					this.Onid_tutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_persona", DbType="Int")]
		public System.Nullable<int> id_persona
		{
			get
			{
				return this._id_persona;
			}
			set
			{
				if ((this._id_persona != value))
				{
					if (this._tbl_personas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_personaChanging(value);
					this.SendPropertyChanging();
					this._id_persona = value;
					this.SendPropertyChanged("id_persona");
					this.Onid_personaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_tutor_tbl_candidato_tutor", Storage="_tbl_candidato_tutor", ThisKey="id_tut", OtherKey="id_tutor")]
		public EntitySet<tbl_candidato_tutor> tbl_candidato_tutor
		{
			get
			{
				return this._tbl_candidato_tutor;
			}
			set
			{
				this._tbl_candidato_tutor.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_personas_tbl_tutor", Storage="_tbl_personas", ThisKey="id_persona", OtherKey="id_per", IsForeignKey=true)]
		public tbl_personas tbl_personas
		{
			get
			{
				return this._tbl_personas.Entity;
			}
			set
			{
				tbl_personas previousValue = this._tbl_personas.Entity;
				if (((previousValue != value) 
							|| (this._tbl_personas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_personas.Entity = null;
						previousValue.tbl_tutor.Remove(this);
					}
					this._tbl_personas.Entity = value;
					if ((value != null))
					{
						value.tbl_tutor.Add(this);
						this._id_persona = value.id_per;
					}
					else
					{
						this._id_persona = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_personas");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_candidato_tutor(tbl_candidato_tutor entity)
		{
			this.SendPropertyChanging();
			entity.tbl_tutor = this;
		}
		
		private void detach_tbl_candidato_tutor(tbl_candidato_tutor entity)
		{
			this.SendPropertyChanging();
			entity.tbl_tutor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_vacunacion")]
	public partial class tbl_vacunacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_vacu;
		
		private string _des_vacu;
		
		private System.Nullable<System.DateTime> _fec_vacu;
		
		private System.Nullable<char> _est_vacu;
		
		private EntitySet<tbl_historia_clinica> _tbl_historia_clinica;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_vacuChanging(int value);
    partial void Onid_vacuChanged();
    partial void Ondes_vacuChanging(string value);
    partial void Ondes_vacuChanged();
    partial void Onfec_vacuChanging(System.Nullable<System.DateTime> value);
    partial void Onfec_vacuChanged();
    partial void Onest_vacuChanging(System.Nullable<char> value);
    partial void Onest_vacuChanged();
    #endregion
		
		public tbl_vacunacion()
		{
			this._tbl_historia_clinica = new EntitySet<tbl_historia_clinica>(new Action<tbl_historia_clinica>(this.attach_tbl_historia_clinica), new Action<tbl_historia_clinica>(this.detach_tbl_historia_clinica));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_vacu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_vacu
		{
			get
			{
				return this._id_vacu;
			}
			set
			{
				if ((this._id_vacu != value))
				{
					this.Onid_vacuChanging(value);
					this.SendPropertyChanging();
					this._id_vacu = value;
					this.SendPropertyChanged("id_vacu");
					this.Onid_vacuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_des_vacu", DbType="VarChar(50)")]
		public string des_vacu
		{
			get
			{
				return this._des_vacu;
			}
			set
			{
				if ((this._des_vacu != value))
				{
					this.Ondes_vacuChanging(value);
					this.SendPropertyChanging();
					this._des_vacu = value;
					this.SendPropertyChanged("des_vacu");
					this.Ondes_vacuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fec_vacu", DbType="Date")]
		public System.Nullable<System.DateTime> fec_vacu
		{
			get
			{
				return this._fec_vacu;
			}
			set
			{
				if ((this._fec_vacu != value))
				{
					this.Onfec_vacuChanging(value);
					this.SendPropertyChanging();
					this._fec_vacu = value;
					this.SendPropertyChanged("fec_vacu");
					this.Onfec_vacuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_est_vacu", DbType="Char(1)")]
		public System.Nullable<char> est_vacu
		{
			get
			{
				return this._est_vacu;
			}
			set
			{
				if ((this._est_vacu != value))
				{
					this.Onest_vacuChanging(value);
					this.SendPropertyChanging();
					this._est_vacu = value;
					this.SendPropertyChanged("est_vacu");
					this.Onest_vacuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_vacunacion_tbl_historia_clinica", Storage="_tbl_historia_clinica", ThisKey="id_vacu", OtherKey="id_vacunacion")]
		public EntitySet<tbl_historia_clinica> tbl_historia_clinica
		{
			get
			{
				return this._tbl_historia_clinica;
			}
			set
			{
				this._tbl_historia_clinica.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_historia_clinica(tbl_historia_clinica entity)
		{
			this.SendPropertyChanging();
			entity.tbl_vacunacion = this;
		}
		
		private void detach_tbl_historia_clinica(tbl_historia_clinica entity)
		{
			this.SendPropertyChanging();
			entity.tbl_vacunacion = null;
		}
	}
	
	public partial class Sp_LoginResult
	{
		
		private int _id_per;
		
		private string _dni_per;
		
		private string _nom_per;
		
		private string _ema_per;
		
		private string _ape_per;
		
		private System.Nullable<int> _id_ro;
		
		private string _des_rol;
		
		private System.Nullable<int> _id_usuario;
		
		private string _user_usu;
		
		private string _pass_usu;
		
		private string _est_per;
		
		private System.Nullable<char> _est_rol;
		
		public Sp_LoginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_per", DbType="Int NOT NULL")]
		public int id_per
		{
			get
			{
				return this._id_per;
			}
			set
			{
				if ((this._id_per != value))
				{
					this._id_per = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dni_per", DbType="VarChar(10)")]
		public string dni_per
		{
			get
			{
				return this._dni_per;
			}
			set
			{
				if ((this._dni_per != value))
				{
					this._dni_per = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom_per", DbType="VarChar(20)")]
		public string nom_per
		{
			get
			{
				return this._nom_per;
			}
			set
			{
				if ((this._nom_per != value))
				{
					this._nom_per = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ema_per", DbType="VarChar(100)")]
		public string ema_per
		{
			get
			{
				return this._ema_per;
			}
			set
			{
				if ((this._ema_per != value))
				{
					this._ema_per = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ape_per", DbType="VarChar(20)")]
		public string ape_per
		{
			get
			{
				return this._ape_per;
			}
			set
			{
				if ((this._ape_per != value))
				{
					this._ape_per = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ro", DbType="Int")]
		public System.Nullable<int> id_ro
		{
			get
			{
				return this._id_ro;
			}
			set
			{
				if ((this._id_ro != value))
				{
					this._id_ro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_des_rol", DbType="VarChar(20)")]
		public string des_rol
		{
			get
			{
				return this._des_rol;
			}
			set
			{
				if ((this._des_rol != value))
				{
					this._des_rol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", DbType="Int")]
		public System.Nullable<int> id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					this._id_usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_usu", DbType="VarChar(20)")]
		public string user_usu
		{
			get
			{
				return this._user_usu;
			}
			set
			{
				if ((this._user_usu != value))
				{
					this._user_usu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass_usu", DbType="VarChar(200)")]
		public string pass_usu
		{
			get
			{
				return this._pass_usu;
			}
			set
			{
				if ((this._pass_usu != value))
				{
					this._pass_usu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_est_per", DbType="VarChar(255)")]
		public string est_per
		{
			get
			{
				return this._est_per;
			}
			set
			{
				if ((this._est_per != value))
				{
					this._est_per = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_est_rol", DbType="Char(1)")]
		public System.Nullable<char> est_rol
		{
			get
			{
				return this._est_rol;
			}
			set
			{
				if ((this._est_rol != value))
				{
					this._est_rol = value;
				}
			}
		}
	}
	
	public partial class Sp_RegistroResult
	{
		
		private int _id_per;
		
		private string _dni_per;
		
		private string _nom_per;
		
		private string _ape_per;
		
		private string _ema_per;
		
		private System.Nullable<int> _id_ro;
		
		private string _des_rol;
		
		private System.Nullable<int> _id_usuario;
		
		private string _user_usu;
		
		private string _pass_usu;
		
		private string _est_per;
		
		private System.Nullable<char> _est_usu;
		
		private System.Nullable<char> _est_rol;
		
		public Sp_RegistroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_per", DbType="Int NOT NULL")]
		public int id_per
		{
			get
			{
				return this._id_per;
			}
			set
			{
				if ((this._id_per != value))
				{
					this._id_per = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dni_per", DbType="VarChar(10)")]
		public string dni_per
		{
			get
			{
				return this._dni_per;
			}
			set
			{
				if ((this._dni_per != value))
				{
					this._dni_per = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom_per", DbType="VarChar(20)")]
		public string nom_per
		{
			get
			{
				return this._nom_per;
			}
			set
			{
				if ((this._nom_per != value))
				{
					this._nom_per = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ape_per", DbType="VarChar(20)")]
		public string ape_per
		{
			get
			{
				return this._ape_per;
			}
			set
			{
				if ((this._ape_per != value))
				{
					this._ape_per = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ema_per", DbType="VarChar(100)")]
		public string ema_per
		{
			get
			{
				return this._ema_per;
			}
			set
			{
				if ((this._ema_per != value))
				{
					this._ema_per = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ro", DbType="Int")]
		public System.Nullable<int> id_ro
		{
			get
			{
				return this._id_ro;
			}
			set
			{
				if ((this._id_ro != value))
				{
					this._id_ro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_des_rol", DbType="VarChar(20)")]
		public string des_rol
		{
			get
			{
				return this._des_rol;
			}
			set
			{
				if ((this._des_rol != value))
				{
					this._des_rol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", DbType="Int")]
		public System.Nullable<int> id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					this._id_usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_usu", DbType="VarChar(20)")]
		public string user_usu
		{
			get
			{
				return this._user_usu;
			}
			set
			{
				if ((this._user_usu != value))
				{
					this._user_usu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass_usu", DbType="VarChar(200)")]
		public string pass_usu
		{
			get
			{
				return this._pass_usu;
			}
			set
			{
				if ((this._pass_usu != value))
				{
					this._pass_usu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_est_per", DbType="VarChar(255)")]
		public string est_per
		{
			get
			{
				return this._est_per;
			}
			set
			{
				if ((this._est_per != value))
				{
					this._est_per = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_est_usu", DbType="Char(1)")]
		public System.Nullable<char> est_usu
		{
			get
			{
				return this._est_usu;
			}
			set
			{
				if ((this._est_usu != value))
				{
					this._est_usu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_est_rol", DbType="Char(1)")]
		public System.Nullable<char> est_rol
		{
			get
			{
				return this._est_rol;
			}
			set
			{
				if ((this._est_rol != value))
				{
					this._est_rol = value;
				}
			}
		}
	}
	
	public partial class Sp_BuscarClaveTemResult
	{
		
		private int _id_usu;
		
		private string _user_usu;
		
		private string _pass_usu;
		
		private System.Nullable<char> _est_usu;
		
		private string _ema_usu;
		
		private string _cltm_usu;
		
		public Sp_BuscarClaveTemResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usu", DbType="Int NOT NULL")]
		public int id_usu
		{
			get
			{
				return this._id_usu;
			}
			set
			{
				if ((this._id_usu != value))
				{
					this._id_usu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_usu", DbType="VarChar(20)")]
		public string user_usu
		{
			get
			{
				return this._user_usu;
			}
			set
			{
				if ((this._user_usu != value))
				{
					this._user_usu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass_usu", DbType="VarChar(50)")]
		public string pass_usu
		{
			get
			{
				return this._pass_usu;
			}
			set
			{
				if ((this._pass_usu != value))
				{
					this._pass_usu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_est_usu", DbType="Char(1)")]
		public System.Nullable<char> est_usu
		{
			get
			{
				return this._est_usu;
			}
			set
			{
				if ((this._est_usu != value))
				{
					this._est_usu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ema_usu", DbType="VarChar(200)")]
		public string ema_usu
		{
			get
			{
				return this._ema_usu;
			}
			set
			{
				if ((this._ema_usu != value))
				{
					this._ema_usu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cltm_usu", DbType="VarChar(10)")]
		public string cltm_usu
		{
			get
			{
				return this._cltm_usu;
			}
			set
			{
				if ((this._cltm_usu != value))
				{
					this._cltm_usu = value;
				}
			}
		}
	}
	
	public partial class Sp_BuscarIdUsuResult
	{
		
		private int _id_usu;
		
		public Sp_BuscarIdUsuResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usu", DbType="Int NOT NULL")]
		public int id_usu
		{
			get
			{
				return this._id_usu;
			}
			set
			{
				if ((this._id_usu != value))
				{
					this._id_usu = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
